name: Create Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Master을 target으로 한 PR이 Merged 상태인지 판단
        if: github.event.pull_request.merged == false
        run: exit 1

      - name: 체크아웃
        uses: actions/checkout@v2

      - name: 현재 최신 릴리즈 가져오기
        id: latest_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.SECRET_GH_TOKEN }}
          view_top: 1

      - name: head가 qa인 경우, 마이너 버전 올리기
        if: ${{ github.head_ref == 'qa' }}
        run: |
          echo "BUMP=minor" >> $GITHUB_ENV

      - name: head가 develop이 아닌 경우(hotfix), 패치 버전 올리기
        if: ${{ github.head_ref != 'qa' }}
        run: |
          echo "BUMP=patch" >> $GITHUB_ENV

      - name: 새로운 릴리즈 태그 계산하기
        id: bump-semver
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ steps.latest_release.outputs.tag_name }}
          level: ${{ env.BUMP }}

      - name: 새로운 릴리즈 만들기
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GH_TOKEN }}
        with:
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
          release_name: ${{ steps.bump-semver.outputs.new_version }}
          body: |
            [Jenkins 파이프라인](https://jenkins.grapeisfruit.com/job/release-pipeline-prod/build)의 SHA 파라미터로 ${{ steps.bump-semver.outputs.new_version }}를 넣어 배포하세요!

            이전 릴리즈와의 diff
            - https://github.com/flex-jonghyuk/github-actions-playground/compare/${{ steps.latest_release.outputs.tag_name }}...${{ steps.bump-semver.outputs.new_version }}
          draft: false
          prerelease: false
